global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 30s

scrape_configs:
***********************************
- job_name: 'FortiGate-101F'
  metrics_path: /metrics
  static_configs:
    - targets:
      - 192.168.11.31:8025

- job_name: 'FortiGate-71F'
  metrics_path: /metrics
  static_configs:
    - targets:
      - 192.168.11.31:8024
***********************************
