{
 "title": "FortiGate 51G",
 "tags": [
  "Router",
  "Fortios"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Temperature °C",
   "type": "stat",
   "gridPos": { "h": 12, "w": 18, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "CPU_ON_DIE_Temperature{job=\"FortiGate-51G\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "Temperature_88E1514{instance=\"192.168.17.201:8026\", job=\"FortiGate-51G\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "Temperature_88E1545{job=\"FortiGate-51G\", instance=\"192.168.17.201:8026\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Uptime{instance=\"192.168.17.201:8026\", job=\"FortiGate-51G\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DISK",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Disk_Usage{instance=\"192.168.17.201:8026\", job=\"FortiGate-51G\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OS Version",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 7 },
   "targets": [
    {
     "expr": "Firmware_Version_info{job=\"FortiGate-51G\"}"
    }
   ]
  },
  {
   "title": "CPU load, %",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "CPU_load{instance=\"192.168.17.201:8026\", job=\"FortiGate-51G\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU load, %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 12 },
   "targets": [
    {
     "expr": "CPU_load{job=\"FortiGate-51G\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory load, %",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Memory_load{instance=\"192.168.17.201:8026\", job=\"FortiGate-51G\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory load, %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 20 },
   "targets": [
    {
     "expr": "Memory_load{job=\"FortiGate-51G\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Curent Sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "Sessions{instance=\"192.168.17.201:8026\", job=\"FortiGate-51G\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}