{
 "title": "FortiGate 101F",
 "tags": [
  "Fortios",
  "Router"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Temperature °C",
   "type": "stat",
   "gridPos": { "h": 12, "w": 13, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "TMP1_External_Temperature{job=\"FortiGate-101F\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "TMP4_ON_DIE_Temperature{job=\"FortiGate-101F\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "CPU_ON_DIE_Temperature{job=\"FortiGate-101F\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "BCM_Switch_Temperature{job=\"FortiGate-101F\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "B50185_Temperature{job=\"FortiGate-101F\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "B50210_1_Temperature{job=\"FortiGate-101F\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "B50210_2_Temperature{job=\"FortiGate-101F\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fan Speed",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "FanStatusSpeed_1{job=\"FortiGate-101F\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "FanStatusSpeed_2{job=\"FortiGate-101F\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PSUs status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "psuStatus_1{job=\"FortiGate-101F\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "psuStatus_2{job=\"FortiGate-101F\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Uptime{job=\"FortiGate-101F\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DISK",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Disk_Usage{job=\"FortiGate-101F\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OS Version",
   "type": "table",
   "gridPos": { "h": 4, "w": 5, "x": 13, "y": 8 },
   "targets": [
    {
     "expr": "Firmware_Version_info{job=\"FortiGate-101F\"}"
    }
   ]
  },
  {
   "title": "CPU load, %",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "CPU_load{job=\"FortiGate-101F\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU load, %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 12 },
   "targets": [
    {
     "expr": "CPU_load{job=\"FortiGate-101F\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory load, %",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Memory_load{job=\"FortiGate-101F\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory load, %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 20 },
   "targets": [
    {
     "expr": "Memory_load{job=\"FortiGate-101F\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sessions / Active Sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "Sessions{job=\"FortiGate-101F\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "Active_Sessions{job=\"FortiGate-101F\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}